// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Woah.Api.Infrastructure.Persistence;


#nullable disable

namespace Woah.Api.Migrations
{
    [DbContext(typeof(WoahDbContext))]
    [Migration("20260228193255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.GameSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.HasIndex("LobbyId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.LobbyEntity", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LobbyId");

                    b.HasIndex("HostPlayerId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.LobbyPlayerEntity", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LobbyId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("LobbyId", "Nick")
                        .IsUnique();

                    b.ToTable("LobbyPlayers");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.PlayerEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nick")
                        .HasColumnType("text");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.PlaylistEntity", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("PlaylistId");

                    b.HasIndex("OwnerPlayerId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.PlaylistTrackEntity", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId", "ItemNumber");

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.RoundCorrectAnswerEntity", b =>
                {
                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("RoundId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("RoundCorrectAnswers");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.RoundEntity", b =>
                {
                    b.Property<Guid>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerNorm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlaylistItemNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNo")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoundId");

                    b.HasIndex("SessionId", "RoundNo")
                        .IsUnique();

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.GameSessionEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Models.LobbyEntity", "Lobby")
                        .WithMany()
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Models.PlaylistEntity", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.LobbyEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Models.PlayerEntity", "HostPlayer")
                        .WithMany()
                        .HasForeignKey("HostPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HostPlayer");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.LobbyPlayerEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Models.LobbyEntity", "Lobby")
                        .WithMany("LobbyPlayers")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Models.PlayerEntity", "Player")
                        .WithMany("LobbyMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.PlaylistEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Models.PlayerEntity", "OwnerPlayer")
                        .WithMany("Playlists")
                        .HasForeignKey("OwnerPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerPlayer");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.PlaylistTrackEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Models.PlaylistEntity", "Playlist")
                        .WithMany("Tracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.RoundCorrectAnswerEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Models.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Models.RoundEntity", "Round")
                        .WithMany("CorrectAnswers")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.RoundEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Models.GameSessionEntity", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.GameSessionEntity", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.LobbyEntity", b =>
                {
                    b.Navigation("LobbyPlayers");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.PlayerEntity", b =>
                {
                    b.Navigation("LobbyMemberships");

                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.PlaylistEntity", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Models.RoundEntity", b =>
                {
                    b.Navigation("CorrectAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
