// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Woah.Api.Infrastructure.Data;

#nullable disable

namespace Woah.Api.Migrations
{
    [DbContext(typeof(WoahDbContext))]
    partial class WoahDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lobby_id");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("lobby_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_player_id");

                    b.Property<short>("MaxPlayers")
                        .HasColumnType("smallint")
                        .HasColumnName("max_players");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HostPlayerId");

                    b.ToTable("lobbies", null, t =>
                        {
                            t.HasCheckConstraint("lobbies_max_players_chk", "max_players BETWEEN 1 AND 10");

                            t.HasCheckConstraint("lobbies_status_chk", "status IN ('waiting','playing','finished')");
                        });
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.LobbyPlayer", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lobby_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nick");

                    b.HasKey("LobbyId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("LobbyId", "Nick")
                        .IsUnique();

                    b.ToTable("lobby_players", (string)null);
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("market");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_player_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerPlayerId");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.PlaylistTrack", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<int>("ItemNo")
                        .HasColumnType("integer")
                        .HasColumnName("item_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InvalidReason")
                        .HasColumnType("text")
                        .HasColumnName("invalid_reason");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_url");

                    b.Property<string>("SpotifyTrackId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spotify_track_id");

                    b.Property<string>("SpotifyUrl")
                        .HasColumnType("text")
                        .HasColumnName("spotify_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TrackJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("track_json");

                    b.HasKey("PlaylistId", "ItemNo");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("PlaylistId", "SpotifyTrackId")
                        .IsUnique()
                        .HasFilter("spotify_track_id IS NOT NULL");

                    b.ToTable("playlist_tracks", (string)null);
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<string>("AnswerNorm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_norm");

                    b.Property<string>("AnswerTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_title");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<int>("PlaylistItemNo")
                        .HasColumnType("integer")
                        .HasColumnName("playlist_item_no");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preview_url");

                    b.Property<DateTimeOffset?>("RevealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revealed_at");

                    b.Property<int>("RoundNo")
                        .HasColumnType("integer")
                        .HasColumnName("round_no");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId", "PlaylistItemNo");

                    b.HasIndex("SessionId", "RoundNo")
                        .IsUnique();

                    b.ToTable("rounds", null, t =>
                        {
                            t.HasCheckConstraint("rounds_state_chk", "state IN ('running','revealed','finished')");
                        });
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.RoundCorrectAnswer", b =>
                {
                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.HasKey("RoundId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RoundId");

                    b.ToTable("round_correct_answers", (string)null);
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.GameSession", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.Lobby", "Lobby")
                        .WithMany()
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Lobby", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.Player", "HostPlayer")
                        .WithMany()
                        .HasForeignKey("HostPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostPlayer");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.LobbyPlayer", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.Lobby", "Lobby")
                        .WithMany("Players")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Playlist", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.Player", "OwnerPlayer")
                        .WithMany()
                        .HasForeignKey("OwnerPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerPlayer");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.PlaylistTrack", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.Playlist", "Playlist")
                        .WithMany("Tracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Round", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.GameSession", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.PlaylistTrack", "PlaylistTrack")
                        .WithMany()
                        .HasForeignKey("PlaylistId", "PlaylistItemNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistTrack");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.RoundCorrectAnswer", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Data.Entities.Round", "Round")
                        .WithMany("CorrectAnswers")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.GameSession", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Lobby", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Playlist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Data.Entities.Round", b =>
                {
                    b.Navigation("CorrectAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
