// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Woah.Api.Infrastructure.Persistence;

#nullable disable

namespace Woah.Api.Migrations
{
    [DbContext(typeof(WoahDbContext))]
    partial class WoahDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.GameSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.HasIndex("LobbyId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.LobbyEntity", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("LobbyId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HostPlayerId");

                    b.ToTable("Lobbies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lobby_MaxPlayers", "\"MaxPlayers\" >= 2 AND \"MaxPlayers\" <= 20");
                        });
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.LobbyPlayerEntity", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("LobbyId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("LobbyId", "Nick")
                        .IsUnique()
                        .HasFilter("\"LeftAt\" IS NULL");

                    b.ToTable("LobbyPlayers", (string)null);
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.PlayerEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.PlaylistEntity", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("PlaylistId");

                    b.HasIndex("OwnerPlayerId");

                    b.ToTable("Playlists", (string)null);
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.RoundCorrectAnswerEntity", b =>
                {
                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GotArtist")
                        .HasColumnType("boolean");

                    b.Property<bool>("GotTitle")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("RoundId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("RoundCorrectAnswers", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoundCorrectAnswer_Points", "\"Points\" >= 0");
                        });
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.RoundEntity", b =>
                {
                    b.Property<Guid>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerArtist")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AnswerArtistNorm")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AnswerNorm")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AnswerTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ArtworkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ItunesTrackId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlaylistItemNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNo")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("RoundId");

                    b.HasIndex("SessionId", "RoundNo")
                        .IsUnique();

                    b.ToTable("Rounds", null, t =>
                        {
                            t.HasCheckConstraint("CK_Round_RoundNo", "\"RoundNo\" >= 1");
                        });
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.GameSessionEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Persistence.Models.LobbyEntity", "Lobby")
                        .WithMany()
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Persistence.Models.PlaylistEntity", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.LobbyEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Persistence.Models.PlayerEntity", "HostPlayer")
                        .WithMany()
                        .HasForeignKey("HostPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HostPlayer");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.LobbyPlayerEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Persistence.Models.LobbyEntity", "Lobby")
                        .WithMany("LobbyPlayers")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Persistence.Models.PlayerEntity", "Player")
                        .WithMany("LobbyMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.PlaylistEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Persistence.Models.PlayerEntity", "OwnerPlayer")
                        .WithMany("Playlists")
                        .HasForeignKey("OwnerPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerPlayer");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.RoundCorrectAnswerEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Persistence.Models.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Woah.Api.Infrastructure.Persistence.Models.RoundEntity", "Round")
                        .WithMany("CorrectAnswers")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.RoundEntity", b =>
                {
                    b.HasOne("Woah.Api.Infrastructure.Persistence.Models.GameSessionEntity", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.GameSessionEntity", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.LobbyEntity", b =>
                {
                    b.Navigation("LobbyPlayers");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.PlayerEntity", b =>
                {
                    b.Navigation("LobbyMemberships");

                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("Woah.Api.Infrastructure.Persistence.Models.RoundEntity", b =>
                {
                    b.Navigation("CorrectAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
